[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "panic=abort",
    "-C", "lto=fat",
    "-C", "opt-level=3",
    "-Z", "stack-protector=none"
]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
